version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/data:/app/data
    command: ["java", "-jar", "/app/app.jar"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - client-dist:/app/dist
    depends_on:
      - server
    command: ["sh", "-c", "while :; do sleep 2073600; done"]

  nginx:
    image: nginx:alpine
    ports:
      - "5173:80"  # Map port 5173 on the host to port 80 in the container
    volumes:
      - client-dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
    command: ["nginx", "-g", "daemon off;"]

volumes:
  client-dist:
